clientApp:
  name: 'api-gateway'

## APP ##
server:
  port : ${SERVER_PORT}
  servlet:
    context-path: /gtw

spring:
  ## DB ##
  datasource:
    url: jdbc:postgresql://${DATABASE_IP}:${DATABASE_PORT}/dbApiGateway
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  ## HIBERNATE ##
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: gtw
    hibernate:
      ddl-auto: none
      show-sql: true
  application:
    name: api-gateway-service
  ## Needed ##
  main:
    web-application-type: reactive
  ## ASYNC MESSAGE BROKERS ##
#  kafka:
#    bootstrap-servers: ${KAFKA_BOOSTRAP_SERVERS}
#    consumer:
#      group-id: ${KAFKA_CONSUMER_GROUP_ID}

# App Properties

eureka:
  client:
    service-url:
      defaultZone: http://${SERVICE_REGISTRY_USERNAME}:${SERVICE_REGISTRY_PASSWORD}@${SERVICE_REGISTRY_URL}:${SERVICE_REGISTRY_PORT}/eureka

## LOG ##
logging:
  level:
    com.pyrosandro.gtw: ${LOGGING_LEVEL}
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

## Automatic hibernate/sql logs
## Test it with a register post and see if it logs more, when properties are set
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE
